"""SPEC §7.T5 check 3a, volumetric appendix — sweep runner + computed tables.

Recomputes the PLATE k/w identifiability numbers with the volumetric
(Beer-Lambert) source of `layered.delta_t_gaussian_volumetric` over the
§6T scoping l_abs grid, and the de-confound w-prior ×-factors through
the IDENTICAL machinery as the headline sweep
(`identifiability.w_prior_factor_to_deconfound`), so the appendix
numbers are commensurable with the ×2.3–×3.2 they interrogate.

Grid economy (stated, validated in-run): the ×-factor sweeps use
SweepConfig(n_t_wax=7) instead of the headline 25 — under a 0.5 mm
plate t_wax is invisible (|∂lnΔT/∂ln t_wax| ≤ 0.01 across the l_abs
grid) and the factor search is w-driven. The worst-deviation l_abs is
re-run at the full 41×25 resolution and both factors are reported side
by side; the surface-flux factor is also recomputed on the thinned grid
so the baseline is apples-to-apples.

Usage:  python -m cavity.thermal.report_3a_volumetric [--out thermal/reports]
Deterministic — no RNG. Output: identifiability_3a_volumetric_computed.md
+ identifiability_3a_volumetric_grids.npz.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np

from cavity.thermal.identifiability import (
    NAMED_POINTS,
    SIGMA_REL,
    FormSweep,
    SweepConfig,
    confounding_mismatch,
    log_sensitivities,
    r_ratio,
    run_form,
    w_prior_factor_to_deconfound,
)
from cavity.thermal.identifiability import FORMS
from cavity.thermal.volumetric_3a import (
    L_ABS_GRID,
    W_SLOPE_ROBUST_BAND,
    named_point_row,
    run_form_volumetric,
)

THIN = SweepConfig(n_t_wax=7)
WORST_CASE_FULLRES_SIGMA = 0.10  # C.3: the de-confound factor is quoted at 10%


def _factor_text(f: float | None) -> str:
    if f is None:
        return "unrescuable by w alone"
    if f == math.inf:
        return "not confounded (w free)"
    return f"×{f:.2f}"


def _named_indices(sweep: FormSweep) -> dict[str, tuple[int, int]]:
    out = {}
    for name, (w, t_wax) in NAMED_POINTS.items():
        i = int(np.argmin(np.abs(np.log(sweep.w_m) - math.log(w))))
        j = int(np.argmin(np.abs(np.log(sweep.t_wax_m) - math.log(t_wax))))
        out[name] = (i, j)
    return out


def build_report(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    add = lines.append
    add("# Check 3a volumetric-source appendix — computed tables")
    add("")
    add("Generated by `python -m cavity.thermal.report_3a_volumetric` "
        "(deterministic, no RNG).")
    add("Engine: `cavity/thermal/layered.py` volumetric extension, anchored by")
    add("`tests/test_thermal_volumetric.py` before this sweep ran (§8 discipline).")
    add("l_abs values are §6T `PumpAbsorptionLength` UNSOURCED-SCOPING values.")
    add("Raw grids: `identifiability_3a_volumetric_grids.npz`.")
    add("")

    # ---- C.2: named-point slopes + R, direct (grid-free) ----
    print("[3a-vol] C.2 named-point sensitivity table ...")
    add("## C.2 PLATE named points × l_abs grid (surface-flux row first)")
    add("")
    add("| point | l_abs | ∂lnΔT/∂ln k | ∂lnΔT/∂ln w | ∂lnΔT/∂ln t_wax | "
        "∂lnΔT/∂ln l_abs | R | w-slope in robust band? |")
    add("|---|---|---|---|---|---|---|---|")
    lo_band, hi_band = W_SLOPE_ROBUST_BAND
    rows_np: dict[str, list[dict]] = {}
    for point, (w, t_wax) in NAMED_POINTS.items():
        s = log_sensitivities("PLATE", w, t_wax)
        r_surf = r_ratio(FORMS["PLATE"], w, t_wax)
        add(
            f"| {point} | surface flux | {s['dlnT_dlnk']:+.3f} | "
            f"{s['dlnT_dlnw']:+.3f} | {s['dlnT_dlntwax']:+.3f} | — | "
            f"{r_surf:.4f} | (reference) |"
        )
        rows_np[point] = []
        for l_abs in L_ABS_GRID:
            row = named_point_row(point, l_abs)
            rows_np[point].append(row)
            in_band = lo_band <= row["dlnT_dlnw"] <= hi_band
            add(
                f"| {point} | {l_abs * 1e6:.0f} µm | {row['dlnT_dlnk']:+.3f} | "
                f"{row['dlnT_dlnw']:+.3f} | {row['dlnT_dlntwax']:+.3f} | "
                f"{row['dlnT_dlnlabs']:+.3f} | {row['r']:.4f} | "
                f"{'yes' if in_band else 'NO'} |"
            )
    add("")

    # worst deviation case (C.3): largest |w-slope − (−1)|
    worst = max(
        (
            (abs(row["dlnT_dlnw"] + 1.0), point, row["l_abs_m"])
            for point, rows in rows_np.items()
            for row in rows
        ),
    )
    add(
        f"Worst w-slope deviation: {worst[1]} at l_abs = {worst[2] * 1e6:.0f} µm "
        f"(|slope − (−1)| = {worst[0]:.3f})."
    )
    add("")

    # ---- surface baseline on the thinned grid ----
    print(f"[3a-vol] surface-flux baseline on thinned grid "
          f"({THIN.n_w}x{THIN.n_t_wax}x3) ...")
    surf_thin = run_form("PLATE", THIN)
    idx = _named_indices(surf_thin)

    # ---- volumetric grid sweeps: x-factors ----
    grids: dict[str, np.ndarray] = {
        "w_m": surf_thin.w_m,
        "t_wax_m": surf_thin.t_wax_m,
        "surface_delta_t": surf_thin.delta_t,
    }
    factors: dict[tuple[str, str, float], float | None] = {}
    confounded_fraction: dict[str, dict[float, float]] = {}

    def collect(tag: str, sweep: FormSweep) -> None:
        mm = confounding_mismatch(sweep.delta_t, "both_free")
        confounded_fraction[tag] = {
            sigma: float(np.mean(mm < sigma)) for sigma in SIGMA_REL
        }
        for name, (i, j) in _named_indices(sweep).items():
            for sigma in SIGMA_REL:
                factors[(tag, name, sigma)] = w_prior_factor_to_deconfound(
                    sweep, i, j, sigma
                )

    collect("surface", surf_thin)
    for l_abs in L_ABS_GRID:
        print(f"[3a-vol] volumetric sweep l_abs = {l_abs * 1e6:.0f} µm "
              f"({THIN.n_w}x{THIN.n_t_wax}x3) ...")
        sweep = run_form_volumetric("PLATE", l_abs, THIN)
        grids[f"vol_l{l_abs * 1e6:.0f}um_delta_t"] = sweep.delta_t
        collect(f"l{l_abs * 1e6:.0f}um", sweep)

    add("## D.1 de-confound w-prior ×-factor (identical machinery as the "
        "headline sweep; thinned t_wax grid, see header)")
    add("")
    add("| source model | point | ×-factor σ=5% | σ=10% | σ=20% | "
        "confounded box fraction (both free) σ=5/10/20% |")
    add("|---|---|---|---|---|---|")
    tags = ["surface"] + [f"l{l * 1e6:.0f}um" for l in L_ABS_GRID]
    for tag in tags:
        cf = confounded_fraction[tag]
        cf_txt = " / ".join(f"{cf[s]:.0%}" for s in SIGMA_REL)
        for name in NAMED_POINTS:
            add(
                f"| {tag} | {name} | "
                + " | ".join(_factor_text(factors[(tag, name, s)]) for s in SIGMA_REL)
                + f" | {cf_txt} |"
            )
    add("")

    # ---- box-wide R range per l_abs (signal identifiability unaffected?) ----
    add("## R over the whole (w, t_wax) box per l_abs")
    add("")
    for l_abs in L_ABS_GRID:
        r_map = FormSweep(
            "PLATE",
            FORMS["PLATE"],
            surf_thin.w_m,
            surf_thin.t_wax_m,
            grids[f"vol_l{l_abs * 1e6:.0f}um_delta_t"],
        ).r_map
        add(
            f"- l_abs = {l_abs * 1e6:.0f} µm: R ∈ [{r_map.min():.3f}, "
            f"{r_map.max():.3f}] (2σ at σ=20% is 0.4 — identifiable-by-signal "
            f"{'everywhere' if r_map.min() > 0.4 else 'NOT everywhere'})."
        )
    add("")

    # ---- D.3 input: first-order joint (w, l_abs) de-confound arithmetic ----
    add("## First-order joint de-confound: l_abs prior needed alongside the "
        "×2.3 w-prior (σ = 10%)")
    add("")
    add("Linearised in log-space from the C.2 slopes (NOT a grid search): a "
        "band-edge k is mimicked iff |s_k·Δln k| ≤ |s_w|·ln f_w + |s_l|·ln f_l "
        "+ ln(1+σ), Δln k = ln√10. With the w-prior at the surface-flux "
        "email ask f_w = 2.3, the largest admissible l_abs prior half-width:")
    add("")
    add("| point | l_abs | f_l (σ=10%) |")
    add("|---|---|---|")
    ln_fw = math.log(2.3)
    sigma = 0.10
    f_l_min = math.inf
    for point, rows in rows_np.items():
        for row in rows:
            budget = abs(row["dlnT_dlnk"]) * math.log(math.sqrt(10.0)) - math.log(
                1.0 + sigma
            )
            rem = budget - abs(row["dlnT_dlnw"]) * ln_fw
            f_l = math.exp(rem / abs(row["dlnT_dlnlabs"])) if rem > 0 else 1.0
            f_l_min = min(f_l_min, f_l)
            add(f"| {point} | {row['l_abs_m'] * 1e6:.0f} µm | ×{f_l:.2f} |")
    add("")
    add(f"Worst case over both points and the whole scoping grid: "
        f"f_l = ×{f_l_min:.2f}.")
    add("")

    # ---- full-resolution validation at the worst deviation l_abs ----
    worst_l = worst[2]
    print(f"[3a-vol] full-resolution validation at l_abs = {worst_l * 1e6:.0f} µm "
          f"(41x25x3) ...")
    full = run_form_volumetric("PLATE", worst_l, SweepConfig())
    add("## Grid-thinning validation (C.3 worst case, full 41×25 grid)")
    add("")
    for name, (i, j) in _named_indices(full).items():
        f_full = w_prior_factor_to_deconfound(full, i, j, WORST_CASE_FULLRES_SIGMA)
        f_thin = factors[(f"l{worst_l * 1e6:.0f}um", name, WORST_CASE_FULLRES_SIGMA)]
        add(
            f"- {name} at l_abs = {worst_l * 1e6:.0f} µm, σ = 10%: full grid "
            f"{_factor_text(f_full)} vs thinned {_factor_text(f_thin)}."
        )
    grids[f"vol_l{worst_l * 1e6:.0f}um_fullres_delta_t"] = full.delta_t
    grids["fullres_t_wax_m"] = full.t_wax_m
    add("")

    np.savez_compressed(
        out_dir / "identifiability_3a_volumetric_grids.npz",
        l_abs_grid_m=np.array(L_ABS_GRID),
        sigma_rel=np.array(SIGMA_REL),
        **grids,
    )
    (out_dir / "identifiability_3a_volumetric_computed.md").write_text(
        "\n".join(lines), encoding="utf-8"
    )
    print(f"[3a-vol] wrote {out_dir / 'identifiability_3a_volumetric_computed.md'}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="thermal/reports", type=Path)
    args = parser.parse_args()
    build_report(args.out)


if __name__ == "__main__":
    main()
